# Generated by Django 5.1.6 on 2025-02-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_answer_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='next_question',
            field=models.IntegerField(default=0),
        ),
    ]
