# Generated by Django 5.1.6 on 2025-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_question_level_alter_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='test_type',
            new_name='test_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='exam',
            name='timerQuestion',
            field=models.IntegerField(default=0),
        ),
    ]
