# Generated by Django 5.1.6 on 2025-02-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_question_video_file_alter_answer_next_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_file',
        ),
        migrations.AddField(
            model_name='exam',
            name='video_file_exam',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
