# Generated by Django 5.1.6 on 2025-02-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_question_video_file_exam_video_file_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_timing',
            field=models.IntegerField(default=0),
        ),
    ]
