# Generated by Django 5.1.6 on 2025-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_question_video_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_timing',
        ),
        migrations.AddField(
            model_name='answer',
            name='video_timing',
            field=models.IntegerField(default=0),
        ),
    ]
