# Generated by Django 5.1.6 on 2025-02-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_question_video_timing_answer_video_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='video_timing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
