# Generated by Django 5.1.6 on 2025-02-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_request', '0002_testrequest_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRequest',
        ),
    ]
